#!/bin/bash
while read version; do
  while read config; do
    git -d ${version}_{$config}
    git branch ${version}_${config}
    git checkout ${version}_${config}
    cat Dockerfile.template | sed "s/\${VERSION}/$version/g" | sed "s/\${CONFIG}/$config/g" > Dockerfile
    git add Dockerfile
    git commit -m "Generated Dockerfile for ${version}_${config}"
    git push origin ${version}_${config}
    git checkout master
  done <buildroot.defconfigs
done <buildroot.versions

